/* Generated By:JavaCC: Do not edit this line. linguagem2019Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface linguagem2019Constants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int PALAVRARESERVADA = 12;
    /**
     * RegularExpression Id.
     */
    int ARITMETICA = 13;
    /**
     * RegularExpression Id.
     */
    int RELACIONAL = 14;
    /**
     * RegularExpression Id.
     */
    int LOGICA = 15;
    /**
     * RegularExpression Id.
     */
    int INTEGER = 16;
    /**
     * RegularExpression Id.
     */
    int REAL = 17;
    /**
     * RegularExpression Id.
     */
    int STRING = 18;
    /**
     * RegularExpression Id.
     */
    int BOOLEAN = 19;
    /**
     * RegularExpression Id.
     */
    int TIPO = 20;
    /**
     * RegularExpression Id.
     */
    int DIGITO = 21;
    /**
     * RegularExpression Id.
     */
    int SIMBOLOSESPECIAIS = 22;
    /**
     * RegularExpression Id.
     */
    int INVALID_LEXICAL = 23;
    /**
     * RegularExpression Id.
     */
    int INVALID_CONST = 24;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;
    /**
     * Lexical state.
     */
    int comentarioemlinha = 1;
    /**
     * Lexical state.
     */
    int multilinecomment = 2;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\"//\"",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"\\f\"",
            "\"/*\"",
            "<token of kind 8>",
            "<token of kind 9>",
            "\"*/\"",
            "<token of kind 11>",
            "<PALAVRARESERVADA>",
            "<ARITMETICA>",
            "<RELACIONAL>",
            "<LOGICA>",
            "<INTEGER>",
            "<REAL>",
            "<STRING>",
            "<BOOLEAN>",
            "<TIPO>",
            "<DIGITO>",
            "<SIMBOLOSESPECIAIS>",
            "<INVALID_LEXICAL>",
            "<INVALID_CONST>",
    };

}
