/* Generated By:JavaCC: Do not edit this line. linguagem2019Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface linguagem2019Constants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int RESERVEDWORD = 12;
    /**
     * RegularExpression Id.
     */
    int IDENTIFIER = 13;
    /**
     * RegularExpression Id.
     */
    int ARITHMETIC = 14;
    /**
     * RegularExpression Id.
     */
    int RELACIONAL = 15;
    /**
     * RegularExpression Id.
     */
    int LOGIC = 16;
    /**
     * RegularExpression Id.
     */
    int INTEGER = 17;
    /**
     * RegularExpression Id.
     */
    int REAL = 18;
    /**
     * RegularExpression Id.
     */
    int STRING = 19;
    /**
     * RegularExpression Id.
     */
    int BOOLEAN = 20;
    /**
     * RegularExpression Id.
     */
    int TYPE = 21;
    /**
     * RegularExpression Id.
     */
    int DIGIT = 22;
    /**
     * RegularExpression Id.
     */
    int LETTER = 23;
    /**
     * RegularExpression Id.
     */
    int SPECIALSYMBOL = 24;
    /**
     * RegularExpression Id.
     */
    int INVALID_LEXICAL = 25;
    /**
     * RegularExpression Id.
     */
    int INVALID_CONST = 26;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;
    /**
     * Lexical state.
     */
    int singlelinecomment = 1;
    /**
     * Lexical state.
     */
    int multilinecomment = 2;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\"//\"",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"\\f\"",
            "\"/*\"",
            "<token of kind 8>",
            "<token of kind 9>",
            "\"*/\"",
            "<token of kind 11>",
            "<RESERVEDWORD>",
            "<IDENTIFIER>",
            "<ARITHMETIC>",
            "<RELACIONAL>",
            "<LOGIC>",
            "<INTEGER>",
            "<REAL>",
            "<STRING>",
            "<BOOLEAN>",
            "<TYPE>",
            "<DIGIT>",
            "<LETTER>",
            "<SPECIALSYMBOL>",
            "<INVALID_LEXICAL>",
            "<INVALID_CONST>",
    };

}
