CREATE DATABASE ecommerce;
CREATE TABLE USUARIO (Id INT NOT NULL GENERATED ALWAYS AS IDENTITY,CODIGO_SEGURANCA INT, DATA_VALIDADE VARCHAR(255),LOGIN VARCHAR(255),NUMERO_CARTAO VARCHAR(255), SENHA VARCHAR(255),PRIMARY KEY (Id));
CREATE TABLE PEDIDO_COMPRA(Id INT NOT NULL GENERATED ALWAYS AS IDENTITY, ID_USER INT references USUARIO(Id), DATA_PEDIDO VARCHAR(255), PRIMARY KEY (Id))
CREATE TABLE ITEM_PEDIDO(Id INT NOT NULL GENERATED ALWAYS AS IDENTITY, ID_PEDIDO INT references PEDIDO_COMPRA(Id), ID_ITEM INT references ITEM(Id), QUANTIDADE INT, PRIMARY KEY (Id));
CREATE TABLE ITEM(Id INT NOT NULL GENERATED ALWAYS AS IDENTITY, DESCRICAO VARCHAR(255), DETALHES VARCHAR(255), NOME VARCHAR(255), PRIMARY KEY (Id));
INSERT INTO USUARIO (login,senha) VALUES ('fabio','fabio');
INSERT INTO PEDIDO_COMPRA (DATA_PEDIDO, ID_USER) VALUES ('19/12/1999',1);
INSERT INTO ITEM (DESCRICAO, DETALHES, NOME) VALUES ('Uma bola de futebol azul com gomos brancos', 'macia', 'Bola azul');
INSERT INTO ITEM (DESCRICAO, DETALHES, NOME) VALUES ('Uma cadeira de praia', 'Madeira', 'Cadeira');
INSERT INTO ITEM_PEDIDO(ID_PEDIDO,ID_ITEM,QUANTIDADE) VALUES (1,1,10);



DROP TABLE ITEM;
DROP TABLE ITEM_PEDIDO;
DROP TABLE PEDIDO_COMPRA;
DROP TABLE USUARIO;
